const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  // path
  startid: state => state.path.startid,
  endid: state => state.path.endid,
  histories: state => state.path.histories,
  maxdegree: state => state.path.maxdegree,
  chosennode: state => state.path.chosennode,
  chosenedge: state => state.path.chosenedge,
  nodelabel: state => state.path.nodelabel,
  edgelabel: state => state.path.edgelabel,
  chosennodelabel: state => state.path.chosennodelabel,
  chosenedgelabel: state => state.path.chosenedgelabel,
  graphnode: state => state.path.graphnode,
  graphedge: state => state.path.graphedge,
  startname: state => state.path.startname,
  endname: state => state.path.endname,
  graphdata: state => state.path.graphdata,
  radio: state => state.path.radio,
  // relation
  // relation_objectnum: state => state.relation.objectnum,
  relation_searchname: state => state.relation.searchname,
  relation_searchid: state => state.relation.searchid,
  // relation_deletename: state => state.relation.deletename,
  // relation_deleteindex: state => state.relation.deleteindex,
  relation_histories: state => state.relation.histories,
  relation_maxdegree: state => state.relation.maxdegree,
  relation_chosennode: state => state.relation.chosennode,
  relation_chosenedge: state => state.relation.chosenedge,
  relation_nodelabel: state => state.relation.nodelabel,
  relation_edgelabel: state => state.relation.edgelabel,
  relation_chosennodelabel: state => state.relation.chosennodelabel,
  relation_chosenedgelabel: state => state.relation.chosenedgelabel,
  relation_graphnode: state => state.relation.graphnode,
  relation_graphedge: state => state.relation.graphedge,
  // relation_startname: state => state.relation.startname,
  relation_graphdata: state => state.relation.graphdata,
  relation_radio: state => state.relation.radio,
  relation_category: state => state.relation.category,
  // search
  search_bigshow3: state => state.search.bigshow3,
  search_nodeid: state => state.search.node_id,
  search_nodename: state => state.search.node_name,
  search_nodelabel: state => state.search.node_label,
  search_options: state => state.search.options,
  search_graphdata: state => state.search.graphdata,
  search_bigshow4: state => state.search.bigshow4,
  search_bigshow5: state => state.search.bigshow5,
  search_node_category: state => state.search.node_category,
  // edge
  edge_label: state => state.edge.edgelabel,
  edge_node_id: state => state.edge.nodeid,
  edge_node_label: state => state.edge.nodelabel,
  // overview
  overview_entity_id: state => state.overview.entity,
  overview_category_name: state => state.overview.category,
  overview_category_label: state => state.overview.label,
  overview_relation_cate: state => state.overview.relation_cate,
  overview_relation_label: state => state.overview.relation_label,
  overview_small_show1: state => state.overview.small_show1,
  overview_small_show2: state => state.overview.small_show2

}
export default getters
